### ISSUE TITLE
TestFlight gone?

### ISSUE THREAD

**Issue by tychoquad** [Sidetalker/SplatPal#30]
Went to update my betas, noticed splatpal was missing from TestFlight. Was this on purpose?

**Comment by Sidetalker** [comment]
I’ve just uploaded a new beta with a version number change - iTunes removed the current build from production and has apparently decided to disappear the icon for my external beta testers. The new beta (only minor fixes + loadout reordering) is in “beta review” which usually only takes about 24 hours. As soon as that passes review, the icon should show back up without any issues. I’ll be working on it over the next week or so and future updates will be instantly approved since the version number will stay the same before the next release.

**Comment by tychoquad** [comment]
Thanks for the update, I was worried you didn’t like me anymore ;)

**Comment by Sidetalker** [comment]
Don't be ridiculous...

**Comment by Sidetalker** [comment]
@tychoquad the app just passed beta review - let me know if it's still not showing up in TestFlight for you

**Comment by tychoquad** [comment]
It's back, thanks!
