### ISSUE TITLE
Apple Watch complications don't load

### ISSUE THREAD

**Issue by tychoquad** [Sidetalker/SplatPal#4]
I don't know if this is a problem with the app, buggy as hell complication system*, or you haven't implemented them yet, (:p) but I can't get the splatpal complications to load.

On the modular and utility faces, the complication just loads in black, except in slots that accommodate text, in which case, it just says SplatPal (big modular fills the other 2 lines with --------------) see screenshot. ![image](https://cloud.githubusercontent.com/assets/16813583/12474041/c7338bb6-c06b-11e5-9962-5d75334a6b9c.png)
I have splatpal loaded into the bottom right complication slot as well

*ive seen this behavior with third party complications before, but a simple phone restart fixed it. No amount of restarting this, reconnecting that has helped me budge it here

**Comment by Sidetalker** [comment]
Complications aren’t yet implemented, I plan to do this Saturday. Sorry I didn’t mention this anywhere in the release notes, I should have disabled them until they were implemented. The Apple Watch app as a whole is not the experience I’d like it to be - it’s difficult to test as I'm developing because all of the remaining issues have to do with the lifecycle of the app and how watchOS manages resources of suspended apps… Hopefully things will get a lot better after this weekend. Thanks for taking the time to send in your feedback and for being a tester!

**Comment by tychoquad** [comment]
I suspected that may have been the case based on how the Notification Center widget was present but just said coming soon for a while there :p 

The app and glance functionally have worked perfect for me so far, no problems with either getting fresh data (which is the problem I most have with watch apps)

I see the app has little black and white icons for the ranked modes, I'm guessing they will be used for the complication icons as well? I'm not sure exactly how the complication APIs work, but I heard that you can get a progress ring similar to the battery indicator. It would be nice if the smaller complications could show the ranked mode icon and have the progress bar show how much longer that mode has.

The demo info in the large modular complication space shows your thinking the same thing as me for that :) you could probably get it to show the turf war maps as well if you use time travel and alternate between displaying the ranked and turf war maps every half an hour. If it's not displaying what you want to see, you could just flick the crown forward and it would display the other

Thank you for doing the watch app, there are still very few good ones, but what you have already implemented is something I know I'm going to use every day

**Comment by Sidetalker** [comment]
Yep, haha - I do have it coded so that it should be showing just a squid icon for small complications and dummy data in the larger complications but that didn’t work initially and I didn’t want to spend more time on getting placeholder content there.

Awesome! There are a couple intermittent bugs that I’m aware of but it’s great that you haven’t been affected by them. The ones you may see are:
1. Watch app itself getting stuck on the squid image screen (force quit by holding power, releasing and holding power again will fix it) 
2. Third page of Watch app screen displaying a 7:00AM - 7:00PM value with only one map (no idea what’s up with this, I think it’s an issue with the data I’m pulling back)
3. Glance occasionally displaying dummy data instead of a loading-type screen (you can tell this is happening when the timer reads 10:00 and isn't counting down)

Those should all be fixed (at least 1 and 3) over the weekend.

Yep, that’s how they’ll work - I plan to implement time travel as well so you can quickly check upcoming modes (or even maps if you have the large modular complication). The progress ring is a great idea, I hadn’t thought about that use case. 

Another great idea for switching back and forth - I was initially thinking this would be a setting (display ranked or turf only). Maybe it should still be a setting (I don’t really care about turf war maps) but with the a third option to alternate them on an interval.

You’re welcome, that really means a lot to me!

**Comment by Sidetalker** [comment]
It turns out the progress rings can’t be attached to a timer, so I can’t realistically make them represent the amount of time remaining in the current mode. Bummer :/

**Comment by tychoquad** [comment]
Couldn’t you break the timer into 20 groups and reduce the size if the ring by 5 by the appropriate interval to simulate it? (assuming the ring is incremented by 100)

**Comment by Sidetalker** [comment]
Yep lol, had just finished implementing this and was going to email you - had a brain fart after setting up one of the text based complications and being able to use a handy timer object to manage the update smoothly.

**Comment by Sidetalker** [comment]
<img width="145" alt="pastedgraphic-1" src="https://cloud.githubusercontent.com/assets/1299693/12537667/84b78016-c292-11e5-8114-e5a6aedc444e.png">
<img width="144" alt="pastedgraphic-2" src="https://cloud.githubusercontent.com/assets/1299693/12537668/866cfb34-c292-11e5-98d2-0ad90328e415.png">

**Comment by tychoquad** [comment]
Looks good! The only thing I would suggest is to use a bit of color, the Modular and utility watch faces support color complications

Also, even though it's unnecessary, could you stick the game mode icon before the text on the big modular complication? It looks a lot better when it's not just text

**Comment by Sidetalker** [comment]
Testing complications is such a nightmare... I'm pushing an update soon, hopefully everything works right

**Comment by tychoquad** [comment]
![image](https://cloud.githubusercontent.com/assets/16813583/12540159/e7d6ff9e-c357-11e5-88e9-a9eeb80e9485.png)
I love it! Thank you!!
